In [1]:
import numpy as np
import pandas as pd

arr = np.array([1,-2,-3,-5,5,4,5.354,6.343])

In [2]:
arr

array([ 1.   , -2.   , -3.   , -5.   ,  5.   ,  4.   ,  5.354,  6.343])

In [3]:
np.abs(arr)

array([ 1.   ,  2.   ,  3.   ,  5.   ,  5.   ,  4.   ,  5.354,  6.343])

In [4]:
np.fabs(arr)

array([ 1.   ,  2.   ,  3.   ,  5.   ,  5.   ,  4.   ,  5.354,  6.343])

In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
arr2 = np.array([6,4,3,2,6])

In [9]:
np.add(arr1,arr2)

array([ 7,  6,  6,  6, 11])

In [11]:
np.subtract(arr1,arr2)

array([-5, -2,  0,  2, -1])

In [12]:
np.fmin(arr1,arr2)

array([1, 2, 3, 2, 5])

In [13]:
np.fmax(arr1,arr2)

array([6, 4, 3, 4, 6])

In [14]:
points = np.arange(-5,5,0.01)

In [15]:
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [16]:
xs,ys = np.meshgrid(points,points)

In [17]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [18]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [30]:
import matplotlib.pyplot as plt
import pylab
%pylab

z = np.sqrt(xs**2+ys**2)
z

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


c:\users\janfer\appdata\local\programs\python\python36\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['pylab']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [31]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

In [36]:
arr

array([[ 1.44439456, -0.4449949 , -0.72400221,  0.28887241],
       [ 0.31687648, -1.34610642, -0.30157943, -0.10570107],
       [ 0.50579912,  0.59821548,  0.85753798, -0.8751468 ],
       [ 0.66973237,  1.28714478, -1.57767085, -1.1890014 ],
       [-0.33996827, -0.7958672 , -1.23408025, -2.94941323]])

In [35]:
np.sum(arr)

-5.9149588441068488

In [37]:
arr.mean()

-0.29574794220534245

In [41]:
arr.sum(1)

array([ 0.56426987, -1.43651044,  1.08640578, -0.80979511, -5.31932895])

In [42]:
arr.cumsum()

array([ 1.44439456,  0.99939966,  0.27539746,  0.56426987,  0.88114635,
       -0.46496007, -0.7665395 , -0.87224057, -0.36644145,  0.23177403,
        1.08931201,  0.21416521,  0.88389758,  2.17104235,  0.5933715 ,
       -0.5956299 , -0.93559817, -1.73146537, -2.96554562, -5.91495884])

In [43]:
np.cumsum(arr)

array([ 1.44439456,  0.99939966,  0.27539746,  0.56426987,  0.88114635,
       -0.46496007, -0.7665395 , -0.87224057, -0.36644145,  0.23177403,
        1.08931201,  0.21416521,  0.88389758,  2.17104235,  0.5933715 ,
       -0.5956299 , -0.93559817, -1.73146537, -2.96554562, -5.91495884])

In [46]:
arr = np.random.randn(100)

In [47]:
(arr>0).sum()

46

In [57]:
arr = np.random.randn(2,3)

In [58]:
arr

array([[-0.10189612,  0.14405896, -1.19550429],
       [-0.23242098,  1.30250589,  0.05771858]])

In [59]:
arr.sort()

In [60]:
arr

array([[-1.19550429, -0.10189612,  0.14405896],
       [-0.23242098,  0.05771858,  1.30250589]])

In [63]:
arr.sort(0)

In [64]:
arr

array([[-1.19550429, -0.10189612,  0.14405896],
       [-0.23242098,  0.05771858,  1.30250589]])

In [65]:
np.ones(3)

array([ 1.,  1.,  1.])

In [73]:
arr = np.random.randint(0,2,size=10)
arr

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [75]:
arr.cumsum()

array([1, 2, 3, 4, 4, 5, 5, 6, 6, 7], dtype=int32)

In [79]:
np.where(arr>0,1,-1).cumsum().max()

4

In [80]:
arr = np.array([1,2,3,4,5])

In [81]:
arr.sum()

15

In [82]:
arr.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)