In [65]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

obj = Series([4,5,6,1])

In [2]:
obj

0    4
1    5
2    6
3    1
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([4, 5, 6, 1], dtype=int64)

In [6]:
obj1 = Series([4,5,-5,3],index=['d','b','a','s'])

In [8]:
obj1.name = 'population'

In [9]:
obj1

d    4
b    5
a   -5
s    3
Name: population, dtype: int64

In [10]:
datas = {'stas':['Oio','Opn','JHI'],'year':[2000,1998,1999],'pop':[1.2,1.4,1.6]}

In [11]:
frame = DataFrame(datas)

In [12]:
frame

pop stas  year
0  1.2  Oio  2000
1  1.4  Opn  1998
2  1.6  JHI  1999

In [15]:
DataFrame(datas,index=['p','s','y'])

pop stas  year
p  1.2  Oio  2000
s  1.4  Opn  1998
y  1.6  JHI  1999

In [16]:
frame.index

RangeIndex(start=0, stop=3, step=1)

In [80]:
frame.ix[0].pop = 1.8

In [81]:
frame['pop'][2] = 2.9

c:\users\janfer\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [84]:
frame

pop stas  year
years                
0      1.9  Oio  2000
1      1.9  Opn  1998
2      2.9  JHI  1999

In [49]:
frame.index.name = 'years'

In [50]:
frame

pop stas  year
years                
0      1.9  Oio  2000
1      1.9  Opn  1998
2      2.9  JHI  1999

In [51]:
frame.values

array([[1.9, 'Oio', 2000],
       [1.9, 'Opn', 1998],
       [2.9, 'JHI', 1999]], dtype=object)

In [52]:
frame.index

RangeIndex(start=0, stop=3, step=1, name='years')

In [53]:
obj = Series(range(3),index=['a','b','c'])

In [54]:
obj

a    0
b    1
c    2
dtype: int32

In [55]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [56]:
obj.index[1]

'b'

In [57]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [58]:
obj.values

array([0, 1, 2])

In [60]:
import numpy as np
index = pd.Index(np.arange(3))

In [61]:
index

Int64Index([0, 1, 2], dtype='int64')

In [62]:
obj = Series([1,2,3],index=index)

In [63]:
obj

0    1
1    2
2    3
dtype: int64

In [64]:
obj

0    1
1    2
2    3
dtype: int64

In [65]:
obj.index is index

True

In [66]:
obj

0    1
1    2
2    3
dtype: int64

In [68]:
obj = Series([2,3,4,6],index=['d','c','f','s'])

In [69]:
obj

d    2
c    3
f    4
s    6
dtype: int64

In [70]:
obj.reindex(['a','b','c','d'])

a    NaN
b    NaN
c    3.0
d    2.0
dtype: float64

In [71]:
obj

d    2
c    3
f    4
s    6
dtype: int64

In [72]:
obj.reindex(['a','b','c','d'],fill_value=0)

a    0
b    0
c    3
d    2
dtype: int64

In [74]:
obj1 = Series(['bb','cc','dd','ee'],index=[0,2,4,7])

In [75]:
obj1

0    bb
2    cc
4    dd
7    ee
dtype: object

In [77]:
obj1.reindex(range(10),method='bfill')

0     bb
1     cc
2     cc
3     dd
4     dd
5     ee
6     ee
7     ee
8    NaN
9    NaN
dtype: object

In [5]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['oaja','Ojka','FS','kKK'],columns=['a','b','c','d'])

In [6]:
data

a   b   c   d
oaja   0   1   2   3
Ojka   4   5   6   7
FS     8   9  10  11
kKK   12  13  14  15

In [106]:
data[data['a']>5]

a   b   c   d
FS    8   9  10  11
kKK  12  13  14  15

In [8]:
data[0:2][['a','b']]

a  b  c  d
oaja  0  1  2  3
Ojka  4  5  6  7

In [9]:
data[data['a']>5]

a   b   c   d
FS    8   9  10  11
kKK  12  13  14  15

In [13]:
data[0:1][['a','b']]

a  b
oaja  0  1

In [27]:
data.ix[['oaja','FS'],['a','b']]

a  b
oaja  0  1
FS    8  9

In [28]:
data.ix[data['a']>5]

a   b   c   d
FS    8   9  10  11
kKK  12  13  14  15

In [31]:
frame = DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Uta','Oij','Thj','Pad'])

In [32]:
frame

b   d   e
Uta  0   1   2
Oij  3   4   5
Thj  6   7   8
Pad  9  10  11

In [33]:
series3 = frame['d']

In [34]:
series3

Uta     1
Oij     4
Thj     7
Pad    10
Name: d, dtype: int32

In [40]:
frame.sub(series3,axis=0)

b  d  e
Uta -1  0  1
Oij -1  0  1
Thj -1  0  1
Pad -1  0  1

In [42]:
f = lambda x: x.max()-x.min()

In [43]:
frame.apply(f)

b    9
d    9
e    9
dtype: int64

In [44]:
frame

b   d   e
Uta  0   1   2
Oij  3   4   5
Thj  6   7   8
Pad  9  10  11

In [45]:
frame.apply(f, axis=1)

Uta    2
Oij    2
Thj    2
Pad    2
dtype: int64

In [47]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [48]:
frame.apply(f)

b   d   e
min  0   1   2
max  9  10  11

In [49]:
obj =  Series(range(4),index=['a','b','c','d'])

In [50]:
obj.sort_index()

a    0
b    1
c    2
d    3
dtype: int32

In [51]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [54]:
frame = DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','b','a','c'])

In [55]:
frame

d  b  a  c
three  0  1  2  3
one    4  5  6  7

In [56]:
frame.sort_index()

d  b  a  c
one    4  5  6  7
three  0  1  2  3

In [57]:
frame.sort_index(axis=1)

a  b  c  d
three  2  1  3  0
one    6  5  7  4

In [66]:
obj = Series([4,7,-3,5])

In [71]:
frame = DataFrame({'b':[4,5,7,3],'a':[0,1,0,1]},index=[1,2,3,4])

In [72]:
frame

a  b
1  0  4
2  1  5
3  0  7
4  1  3

In [81]:
frame.sort_values(by='a',ascending=False)

a  b
2  1  5
4  1  3
1  0  4
3  0  7

In [80]:
frame.sort_values(by=['a','b'])

a  b
1  0  4
3  0  7
4  1  3
2  1  5

In [82]:
obj = Series([7,3,-5,6,0,4])

In [83]:
obj.rank()

0    6.0
1    3.0
2    1.0
3    5.0
4    2.0
5    4.0
dtype: float64

In [84]:
obj.rank(method='first')

0    6.0
1    3.0
2    1.0
3    5.0
4    2.0
5    4.0
dtype: float64